// <auto-generated />
using System;
using API_devbank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_devbank.Migrations
{
    [DbContext(typeof(DevbankContext))]
    [Migration("20260418045906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_devbank.Models.TabelaConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("saldo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "FK__tabela_usuarios");

                    b.ToTable("tabela_contas", (string)null);
                });

            modelBuilder.Entity("API_devbank.Models.TabelaTransaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContaDestinoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("conta_destino_id");

                    b.Property<int?>("ContaOrigemId")
                        .HasColumnType("int(11)")
                        .HasColumnName("conta_origem_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('D','S','T')")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContaOrigemId" }, "FK_tabela_transacoes_tabela_contas");

                    b.HasIndex(new[] { "ContaDestinoId" }, "FK_tabela_transacoes_tabela_contas_2");

                    b.ToTable("tabela_transacoes", (string)null);
                });

            modelBuilder.Entity("API_devbank.Models.TabelaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<ulong>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasColumnName("isAtivo")
                        .HasDefaultValueSql("b'1'");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('C','A')")
                        .HasColumnName("perfil")
                        .HasDefaultValueSql("'C'");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "CPF")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("tabela_usuarios", (string)null);
                });

            modelBuilder.Entity("API_devbank.Models.TabelaConta", b =>
                {
                    b.HasOne("API_devbank.Models.TabelaUsuario", "IdUsuarioNavigation")
                        .WithMany("TabelaConta")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__tabela_usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("API_devbank.Models.TabelaTransaco", b =>
                {
                    b.HasOne("API_devbank.Models.TabelaConta", "ContaDestino")
                        .WithMany("TabelaTransacoContaDestinos")
                        .HasForeignKey("ContaDestinoId")
                        .HasConstraintName("FK_tabela_transacoes_tabela_contas_2");

                    b.HasOne("API_devbank.Models.TabelaConta", "ContaOrigem")
                        .WithMany("TabelaTransacoContaOrigems")
                        .HasForeignKey("ContaOrigemId")
                        .HasConstraintName("FK_tabela_transacoes_tabela_contas");

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("API_devbank.Models.TabelaConta", b =>
                {
                    b.Navigation("TabelaTransacoContaDestinos");

                    b.Navigation("TabelaTransacoContaOrigems");
                });

            modelBuilder.Entity("API_devbank.Models.TabelaUsuario", b =>
                {
                    b.Navigation("TabelaConta");
                });
#pragma warning restore 612, 618
        }
    }
}
